[package]
name = "rew-qrew-stub"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0" }
rew-runtime = { path = "/home/makano/workspace/rew-rust/rew-runtime" }
anyhow = "1.0.96"
