[package]
name = "archiveman"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
zip = "0.6"
tar = "0.4"
flate2 = "1.0"
xz2 = "0.1"
bzip2 = "0.4"
zstd = "0.13"

[build-dependencies]
cc = "1.0"
